# Generated by Django 2.0.8 on 2018-10-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_member_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
