# Generated by Django 2.0.8 on 2019-11-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20181018_0552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='researchgroup',
            options={'ordering': ['order']},
        ),
    ]
