# Generated by Django 2.0.8 on 2019-11-14 07:22

import bio2vec.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('original_dataset', models.CharField(blank=True, max_length=255, null=True)),
                ('original_description', models.TextField(blank=True, null=True)),
                ('creators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, null=True, size=None)),
                ('contributors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, null=True, size=None)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, null=True, size=None)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('citation', models.CharField(blank=True, max_length=127, null=True)),
                ('measurementTechnique', models.CharField(blank=True, max_length=127, null=True)),
                ('evaluated_in', models.CharField(blank=True, max_length=127, null=True)),
                ('indexed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_datasets', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Datasets',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=31)),
                ('embeddings_file', models.FileField(upload_to=bio2vec.models.dataset_directory_path)),
                ('embedding_size', models.PositiveIntegerField()),
                ('license', models.CharField(choices=[(('CC0',), ('CC0',)), ('CC BY', 'CC BY'), ('CC BY-NC', 'CC BY-NC')], default=('CC0',), max_length=31)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_distributions', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='bio2vec.Dataset')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_distributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Datasets',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=127)),
                ('iri', models.CharField(db_index=True, max_length=127)),
                ('alternative_iris', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, null=True, size=None)),
                ('name', models.CharField(max_length=127)),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, null=True, size=None)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('pca_x', models.FloatField(default=0.0)),
                ('pca_y', models.FloatField(default=0.0)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='bio2vec.Distribution')),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('distribution', 'iri')},
        ),
    ]
