# Generated by Django 2.0.8 on 2018-10-03 06:28

import bio2vec.models
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('entity_types', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None)),
                ('creators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, null=True, size=None)),
                ('contributors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, null=True, size=None)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('source_link', models.CharField(blank=True, max_length=255, null=True)),
                ('original_dataset', models.CharField(blank=True, max_length=255, null=True)),
                ('publications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, null=True, size=None)),
                ('experiment', models.CharField(blank=True, max_length=127, null=True)),
                ('model', models.CharField(blank=True, max_length=127, null=True)),
                ('embeddings_file', models.FileField(upload_to=bio2vec.models.dataset_directory_path)),
                ('indexed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_datasets', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Datasets',
            },
        ),
    ]
