# Generated by Django 2.0.8 on 2018-10-03 13:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio2vec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iri', models.CharField(db_index=True, max_length=127)),
                ('alternative_iris', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, null=True, size=None)),
                ('entity_type', models.CharField(max_length=127)),
                ('label', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, null=True)),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('pca_x', models.FloatField(default=0.0)),
                ('pca_y', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.AlterField(
            model_name='dataset',
            name='entity_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=63), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='entity',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='bio2vec.Dataset'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('dataset', 'iri')},
        ),
    ]
