# Generated by Django 2.0.8 on 2019-11-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio2vec', '0002_auto_20191119_0702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'verbose_name_plural': 'Distributions'},
        ),
        migrations.AlterField(
            model_name='distribution',
            name='license',
            field=models.CharField(choices=[('CC0', 'CC0'), ('CC BY', 'CC BY'), ('CC BY-NC', 'CC BY-NC')], default='CC0', max_length=31),
        ),
    ]
