# Generated by Django 2.0.8 on 2018-10-03 13:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio2vec', '0002_auto_20181003_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='entity_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, null=True, size=None),
        ),
    ]
